function result = execute_pipeline(inputData, cfg)
%EXECUTE_PIPELINE Minimal executable pipeline skeleton.
%   This function orchestrates stages only and keeps contracts stable.

if nargin < 2 || isempty(cfg)
    cfg = get_default_config();
end

validate_inputs(inputData);

% Keep outputs structured for extensibility and testability.
result = struct();
result.raw = struct(...
    'data', inputData.data, ...
    'fs', inputData.fs, ...
    'timestamp', inputData.timestamp, ...
    'type', inputData.type, ...
    'meta', inputData.meta);

% Placeholder pre-processing stage (pass-through for MVP).
result.preprocessed = struct('data', inputData.data, 'meta', struct('status', 'pass-through'));

if cfg.pipeline.enableFeatureExtraction
    preprocessedFft = compute_fft(result.preprocessed.data, result.raw.fs);

    % Keep spectrum/peak contract stable for existing views.
    result.features = struct('spectrum', preprocessedFft.spectrum, 'meta', struct('status', 'computed-fft'));
    result.peaks = preprocessedFft.peaks;

    % Compare-oriented cached outputs (no rendering-time recomputation).
    if isequal(result.raw.data(:), result.preprocessed.data(:))
        rawFft = preprocessedFft;
    else
        rawFft = compute_fft(result.raw.data, result.raw.fs);
    end
    result.compare = struct(...
        'signal', struct(...
            'raw', result.raw.data(:), ...
            'processed', result.preprocessed.data(:), ...
            'axis', struct('name', 'sample', 'unit', 'index')), ...
        'spectrum', struct(...
            'raw', rawFft.spectrum, ...
            'processed', preprocessedFft.spectrum), ...
        'threshold', struct(...
            'pre', preprocessedFft.spectrum.magnitude, ...
            'post', []), ...
        'meta', struct(...
            'thresholdComparisonAvailable', false, ...
            'status', 'cached-from-pipeline'));
else
    result.features = struct('items', [], 'meta', struct('status', 'disabled'));
    result.peaks = struct('items', [], 'count', 0, 'meta', struct('status', 'disabled'));
    result.compare = struct(...
        'signal', struct('raw', [], 'processed', [], 'axis', struct('name', 'sample', 'unit', 'index')), ...
        'spectrum', struct('raw', struct(), 'processed', struct()), ...
        'threshold', struct('pre', [], 'post', []), ...
        'meta', struct('thresholdComparisonAvailable', false, 'status', 'feature-extraction-disabled'));
end

result.display = struct('series', [], 'axes', struct(), 'meta', struct('status', 'prepared-by-visualization-layer'));

result.log = struct(...
    'messages', {{'execute_pipeline completed run'}}, ...
    'warnings', {{}}, ...
    'errors', {{}});

result.meta = struct(...
    'pipelineVersion', cfg.meta.version, ...
    'runtimeMode', cfg.runtime.mode, ...
    'completedAt', datetime('now', 'TimeZone', 'local'));
end
