function bearing = build_bearing_maps_placeholder(state)
%BUILD_BEARING_MAPS_PLACEHOLDER Create placeholder bearing map contracts.
%   No final bearing algorithm is implemented here.

nFrames = size(state.waterfall.magnitudeMatrix, 1);
nBins = size(state.waterfall.magnitudeMatrix, 2);
if isempty(nFrames); nFrames = 0; end
if isempty(nBins); nBins = 0; end

bearingAxis = linspace(-90, 90, max(nBins, 1))';

bearing = struct();
bearing.frequencyMap = struct(...
    'bearingDeg', bearingAxis, ...
    'frequencyHz', state.waterfall.frequencyHz, ...
    'magnitude', nan(numel(bearingAxis), numel(state.waterfall.frequencyHz)), ...
    'meta', struct('status', 'placeholder'));

bearing.timeMap = struct(...
    'bearingDeg', bearingAxis, ...
    'frameIdx', (1:nFrames)', ...
    'magnitude', nan(max(nFrames,1), numel(bearingAxis)), ...
    'meta', struct('status', 'placeholder'));
end
