function state = create_app_state()
%CREATE_APP_STATE Initialize shared app/session state for dashboard workflow.

state = struct();
state.current_view = 'Spectrum';
state.current_preset = 'Quick Check';
state.current_frame_idx = 0;
state.selected_frame_idx = 0;
state.threshold_enabled = false;
state.threshold_value = 0.5;

% Preset-driven UI emphasis state.
state.panel_emphasis = struct(...
    'mainView', true, ...
    'summaryCard', true, ...
    'qualityCard', false, ...
    'eventStrip', true);

state.current_input = struct();
state.current_result = struct();

% Future-ready TCP integration placeholders (no runtime receiver implemented).
state.tcp = struct(...
    'contract', get_tcp_input_contract(), ...
    'enabled', false, ...
    'last_packet_meta', struct(), ...
    'packet_meta_history', {{}}, ...
    'status', 'idle');

state.current_input = struct();
state.current_result = struct();

% Cached history for frame-centric inspection views.
state.waterfall = struct(...
    'frequencyHz', [], ...
    'magnitudeMatrix', [], ...
    'frame_indices', [], ...
    'max_history_frames', inf, ...
    'hold_enabled', false, ...
    'hold_frame_indices', [], ...
    'overlay', struct(...
        'showCurrentMarker', true, ...
        'showMaxHold', false, ...
        'showMeanHold', false));
state.frame_history = {};
state.quality_history = [];
state.detection_history = {};
state.peak_trend = struct(...
    'frameIdx', {}, ...
    'strongestPeakFrequencyHz', {}, ...
    'strongestPeakMagnitude', {});
state.bearing = build_bearing_maps_placeholder(state);

state.frame_quality_summary = struct(...
    'nanOrInfPresent', false, ...
    'inputLength', 0, ...
    'inputLengthValid', false, ...
    'rms', NaN, ...
    'energy', NaN, ...
    'dcOffset', NaN, ...
    'peakAmplitude', NaN, ...
    'clippingRatio', NaN, ...
    'clippingDetected', false, ...
    'decodeStatus', 'unknown', ...
    'continuityStatus', 'unknown', ...
    'qualityLabel', 'unknown');

state.detection_summary = struct(...
    'strongestPeakFrequencyHz', NaN, ...
    'strongestPeakMagnitude', NaN, ...
    'top3Peaks', struct('frequencyHz', {}, 'magnitude', {}), ...
    'thresholdEnabled', false, ...
    'thresholdValue', 0.5, ...
    'thresholdMargin', NaN);

state.event_log = {};
state.last_update_time = NaT;
state.last_issue = struct('level', '', 'message', '');
state.last_error_or_warning = struct('level', '', 'message', '');
state.last_exports = struct('figurePng', '', 'resultMat', '', 'snapshotMat', '', 'summaryCsv', '');
    'hold_enabled', false, ...
    'hold_frame_indices', []);
state.frame_history = {};
state.quality_history = [];
state.peak_trend = [];
state.bearing = build_bearing_maps_placeholder(state);

state.frame_quality_summary = struct(...
    'rms', NaN, ...
    'peakAmplitude', NaN, ...
    'clippingRatio', NaN, ...
    'qualityLabel', 'unknown');

state.event_log = {};
state.last_update_time = NaT;
state.last_issue = struct('level', '', 'message', '');
end
