function preset = get_preset_definition(presetName)
%GET_PRESET_DEFINITION Return preset defaults for app-shell usability.

presetName = char(presetName);

switch presetName
    case 'Quick Check'
        preset = struct(...
            'name', 'Quick Check', ...
            'defaultMainView', 'Spectrum', ...
            'thresholdEnabled', false, ...
            'thresholdValue', 0.5, ...
            'emphasis', struct('mainView', true, 'summaryCard', true, 'qualityCard', false, 'eventStrip', true));
    case 'Detection'
        preset = struct(...
            'name', 'Detection', ...
            'defaultMainView', 'Spectrum', ...
            'thresholdEnabled', true, ...
            'thresholdValue', 0.2, ...
            'emphasis', struct('mainView', true, 'summaryCard', true, 'qualityCard', true, 'eventStrip', true));
    case 'History'
        preset = struct(...
            'name', 'History', ...
            'defaultMainView', 'Waterfall', ...
            'thresholdEnabled', false, ...
            'thresholdValue', 0.5, ...
            'emphasis', struct('mainView', true, 'summaryCard', false, 'qualityCard', false, 'eventStrip', true));
    case 'Debug'
        preset = struct(...
            'name', 'Debug', ...
            'defaultMainView', 'Frame Quality', ...
            'thresholdEnabled', true, ...
            'thresholdValue', 0.1, ...
            'emphasis', struct('mainView', true, 'summaryCard', true, 'qualityCard', true, 'eventStrip', true));
    otherwise
        error('get_preset_definition:UnknownPreset', 'Unknown preset: %s', presetName);
end
end
