function cfg = get_default_config()
%GET_DEFAULT_CONFIG Return baseline configuration for the pipeline.
%   Keep this file focused on config definition only.

cfg = struct();

% Runtime mode can be switched later between 'batch' and 'realtime'.
cfg.runtime = struct(...
    'mode', 'batch', ...
    'verbose', true);

% Pipeline-level feature toggles (placeholder for future growth).
cfg.pipeline = struct(...
    'enablePreprocess', true, ...
    'enableFeatureExtraction', true, ...
    'enablePeakDetection', true, ...
    'enableDisplayPrep', true);

% Metadata defaults to keep output contracts deterministic.
cfg.meta = struct(...
    'project', 'Matlab_Visualize', ...
    'version', '0.1.0', ...
    'createdBy', 'get_default_config');
end
