function example_record_TestInputType()
%EXAMPLE_RECORD_TESTINPUTTYPE TestInputType 수신/저장 예시.

setup_project_paths();

% 사용자 환경에 맞는 헤더 경로 지정
headerPath = 'your_protocol_header.h';

srv = EthTcpServer( ...
    'Port', 5000, ...
    'ChecksumMode', 'byte', ...
    'PointerSizeBytes', 8, ...
    'PointerMatType', 'uint64');

schema = EthTcpServer.schemaFromHeader(headerPath, 'TestInputType', ...
    'StripLeadingHeaderField', true, ...
    'FlattenStructs', true);

srv.registerTopic(10, schema, @(msg,meta) eth_rx_save(msg, meta, ...
    'Key', 'topic10', ...
    'MatFile', fullfile('data','output','rx','topic10_TestInputType.mat')));

srv.start();
disp('EthTcpServer started. Stop manually with srv.stop().');
end
